name: grm-releaser

on:
  push:
    tags: ['v*']

jobs:
  grm-releaser:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - names: Extra Changelog
        run: |
          CHANGELOG=$(awk -v ver=$(awk -F'"' '/"version": ".+"/{ print $4; exit; }' package.json) '/^## / { if (p) { exit }; if ($2 == ver) { p=1; next} } p' CHANGELOG.md)
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install chocolatey
        run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: Install package tools
        run: choco install upx wixtoolset

      - name: Make All
        run: |
          set Path=%Path%;C:\Program Files (x86)\WiX Toolset v3.11\bin\
          mingw32-make
        shell: cmd

      - name: Create Github Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload release binaries
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./build/*"]'
